# Digital Ocean App Platform Configuration
# This file ensures reliable deployment with proper resource allocation

name: guestbook-app
services:
- name: web
  source_dir: /
  github:
    repo: kristiawan6/guestbookapp
    branch: main
    deploy_on_push: true
  
  # Build configuration
  build_command: |
    npm ci --only=production
    npx prisma generate
    npm run build
  
  # Runtime configuration
  run_command: npm start
  
  # Environment settings
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  
  # Health check configuration
  health_check:
    http_path: /api/health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  
  # HTTP configuration
  http_port: 3000
  
  # Routes
  routes:
  - path: /
    preserve_path_prefix: true
  
  # Environment variables (set these in DO dashboard)
  envs:
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: NEXTAUTH_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: NEXTAUTH_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: RESEND_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: EMAIL_FROM
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: CLOUDINARY_CLOUD_NAME
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: CLOUDINARY_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: CLOUDINARY_API_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: WHATSAPP_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: WHATSAPP_PHONE_NUMBER_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: JWT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET

# Database configuration
databases:
- name: guestbook-db
  engine: PG
  version: "14"
  size: db-s-dev-database
  num_nodes: 1
  
# Static site configuration (for assets)
static_sites:
- name: assets
  source_dir: /public
  github:
    repo: your-username/guestbookapp
    branch: main
  build_command: echo "Static assets"
  output_dir: /public
  
# Domain configuration
domains:
- domain: your-domain.com
  type: PRIMARY
  wildcard: false
  zone: your-domain.com